name: gbaenv
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - openssl=1.1.1b=he774522_1
  - pip=19.0.3=py37_0
  - python=3.7.3=h8c8aaf0_0
  - setuptools=40.8.0=py37_0
  - sqlite=3.27.2=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wheel=0.33.1=py37_0
  - wincertstore=0.2=py37_0
  - pip:
    - asn1crypto==0.24.0
    - attrs==19.1.0
    - automat==0.7.0
    - cffi==1.12.2
    - constantly==15.1.0
    - cryptography==2.6.1
    - cssselect==1.0.3
    - hyperlink==18.0.0
    - idna==2.8
    - incremental==17.5.0
    - lxml==4.3.3
    - parsel==1.5.1
    - pillow==6.0.0
    - pyasn1==0.4.5
    - pyasn1-modules==0.2.4
    - pycparser==2.19
    - pydispatcher==2.0.5
    - pyhamcrest==1.9.0
    - pyopenssl==19.0.0
    - pypiwin32==223
    - pywin32==224
    - queuelib==1.5.0
    - scrapy==1.6.0
    - service-identity==18.1.0
    - six==1.12.0
    - sqlalchemy==1.3.2
    - twisted==18.9.0
    - w3lib==1.20.0
    - zope-interface==4.6.0


